# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyShare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyShare
   pod 'RxSwift',    '~> 4.0'
   pod 'RxCocoa',    '~> 4.0'
   pod 'GRDB.swift'

  target 'EasyShareTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'EasyShareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
